edition: 1.0.0 #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: fc-stable-diffusion
access: default
vars:
  imageUrl: registry.cn-shanghai.aliyuncs.com/aliyun-fc/fc-facechain:v1
  region: cn-shanghai
  service:
    name: "fc-facechain"
    description: 'facechain 部署到函数计算'
    internetAccess: true
    nasConfig: auto
    # logConfig: auto

services:
  facechain:
    component: fc
    actions: 
      post-deploy: 
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: facechain
        description: facechain 函数
        handler: index.handler
        timeout: 600
        diskSize: 512
        caPort: 7860
        instanceType: fc.gpu.tesla.1
        runtime: custom-container
        cpu: 8
        customContainerConfig:
          args: ''
          accelerationType: Default
          image: ${vars.imageUrl}
          accelerationInfo:
            status: Preparing
          command: ''
          webServerMode: true
        instanceConcurrency: 100
        memorySize: 32768
        gpuMemorySize: 16384
        asyncConfiguration: {}
        environmentVariables:
      triggers:
        - name: defaultTrigger
          description: ''
          type: http
          qualifier: LATEST
          config:
            methods:
              - GET
              - POST
              - PUT
              - DELETE
            authType: anonymous
            disableURLInternet: false
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
  initial:
    component: fc
    actions: 
      post-deploy:
        - component: fc invoke --service_name ${this.output.service_name} --function ${this.output.function_name} 
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: init
        description: 模型初始化函数
        handler: index.handler
        timeout: 3600
        diskSize: 512
        codeUri: './initial'
        runtime: python3.9
        cpu: 16
        instanceConcurrency: 100
        memorySize: 32768
